version: '3.8'
services:
  # Next.js service definition
  frontend:
    build: ./frontend # Path to the directory containing the Dockerfile for Next.js
    ports:
      - '3000:3000' # Map port 3000 on the host to port 3000 in the container
    volumes:
      - ./frontend:/app # Mount the frontend directory to the /app directory in the container
      - /app/node_modules # Use a volume for node_modules to avoid overwriting the container's version
    environment:
      - NODE_ENV=development

  # FastAPI service definition
  api:
    build: ./API/yamlenv # Path to the directory containing the Dockerfile for FastAPI
    ports:
      - '8000:8000' # Map port 8000 on the host to port 8000 in the container
    volumes:
      - ./API:/app # Mount the API directory to the /app directory in the container
    depends_on:
      - db # Ensure the database is started before the API service

  # PostgreSQL service definition
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdbname
    ports:
      - '5432:5432' # Optional: Expose PostgreSQL port for local connections

volumes:
  postgres_data: # Named volume to persist PostgreSQL data