name: Python application test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Set to your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ./api  # Specify the working directory here

    - name: Run tests
      run: |
        python -m pytest
      working-directory: ./api  # Specify the working directory for tests as well
