name: Python API testing

on:
  pull_request:
    branches: [ main ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: sudo apt-get update && sudo apt-get install docker-compose

    - name: Build and run with Docker Compose
      run: docker-compose up -d

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Set to your Python version

    - name: Cache Python dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip  # This path depends on the OS and the Python environment
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: API  # Specify the working directory here

    - name: Run tests
      run: |
        python -m pytest
      working-directory: API  # Specify the working directory for tests as well
